config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  put 'application/locale/:locale', to: 'application#locale', as: "set_locale"

  get '/', to:'tasks#index'
  # resources :tasks do
  #   get 'tasks/new', to: 'tasks#new'
  #   post 'tasks/create', to: 'tasks#create'
  # end
  get 'tasks/new', to: 'tasks#new', as:'new_task'
  get 'tasks/edit', to: 'tasks#edit', as:'edit_task'
  post 'tasks/new', to: 'tasks#create', as:'create_task'
  post 'tasks/update/:id', to: 'tasks#update', as:'update_task'
  delete 'tasks/delete/:id', to:'tasks#delete', as:'delete_task'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, length: { minimum: 3 }
  enum :importance => [:high, :medium, :low]
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks

#  def set_lang(lang)
#    I18n.locale = lang || I18n.default_locale
#    self.lang = lang
#    self.save
#  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action  :set_locale, :authenticate_user!
  #protect_from_forgery with: :exception

  protect_from_forgery prepend: true
#  def set_locale
 #   I18n.locale = params[:locale] || session[:locale] || I18n.default_locale
    #if user_signed_in?
    #  I18n.locale = current_user.locale
   # end
 #   session[:locale] = I18n.locale
 # end

 # def default_url_options(options = {})
 #   { locale: I18n.locale }.merge options
 # end

 # def locale
  #  I18n.locale = params[:locale] || I18n.default_locale
 #   if current_user
 #     current_user.update!(locale: params[:locale])
  #  end
  #  redirect_to(request.env["HTTP_REFERER"])
 # end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #def index
   # @tasks = current_user.tasks.order("importance ASC").all
   #  respond_to do |format|
   #    format.html{render 'tasks/index'}
   #    format.json{render :json => {tasks: @tasks}}
   # end
  #end

  def index
    @tasks = current_user.tasks.order("expiry").all
    respond_to do |format|
      format.html {  }
      format.json { render json: @tasks, status: :ok}
    end
  end

  def create
    current_user.tasks.create( task_create_params)
    redirect_to '/'
  end

  def update
    task = current_user.tasks.find_by(id: params[:id])
    if task && params[:task]
      task.update!(task_update_params)
    end
    redirect_to '/'
  end

  def delete
    task = current_user.tasks.find_by(id: params[:id])
    if task
      task.destroy!
    end
  end

  def edit
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to '/'
    end
  end

  def task_update_params
    params.require(:task).permit(:name, :description, :importance, :expiry, :done)
  end


  def task_create_params
    params.require(:task).permit(:name, :description, :importance, :expiry, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstCrud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <!--<div style="justify-content: space-between; display: flex">-->
  <!-- <div>-->
     <!-- <%= link_to "En", set_locale_path(locale: "en"), method: :put %> | -->
    <!--  <%= link_to "Ru", set_locale_path(locale: "ru"), method: :put %> -->
  <!-- </div>-->
  <!-- </div>-->

  <%= yield %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div align="center"><h2>Edit</h2></div>>
<%= form_for @task, url: update_task_path(@task.id),  method: :post do |f| -%>
      <p>   <%= f.hidden_field :id, value: @task.id %></p>
      <p> <%= f.text_field :name, value: @task.name %></p>
      <p>  <%= f.text_field :description, value: @task.description %></p>
      <p> <%= f.text_field :importance, placeholder: 'importance' %></p>
      <p> <%= f.date_select :expiry, order: [:day, :month, :year] %></p>
      <p>  <%= f.check_box :done %></p>
      <p>  <%= f.submit "save" %>
<% end %>

<%= link_to'Back', '/' %>

app/views/tasks/index.html.erb
<!--<div>-->
  <!--<%= link_to'New task', 'tasks/new' %>-->
  <!--<% @tasks.each do |task| %>-->
      <!--<div>-->
        <!--<%= task.name %>-->
        <!--<%= link_to 'update task', edit_task_path(id: task.id), method: :get%>-->
        <!--<%= link_to 'delete task', delete_task_path(id: task.id), method: :delete %>-->
      <!--</div>-->
  <!--<% end %>-->
<!--</div>-->

<!-- <%= link_to t('new_task'), 'tasks/new' %>-->
<!--  <% @tasks.each do |task| %>-->
    <!--    <div>-->
        <!--    <%= task.name %>-->
        <!--    <td><%= task.done %></td>-->
        <!--    <%= link_to 'update task', edit_task_path(id: task.id)%>-->
        <!--      <%= link_to 'delete task', delete_task_path(id: task.id), method: :delete %>-->
        <!--     </div>
    <!--  <% end %>-->


<div>
  <div>
    <%= current_user.email %>
  </div>

  <%= link_to t('new_task'), 'tasks/new' %>
  <div align="center">
    <table border = "1" style="width:100%">
      <tr>
        <td><%= t :status %></td>
        <td><%= t :name %></td>
        <td><%= t :description %></td>
        <td><%= t :importance %></td>
        <td><%= t :expiry %></td>
      </tr>
      <% @tasks.each do |task| %>
          <tr>
            <% if task.done%>
                <td><%= t :done%></td>
            <% else task.done%>
                <td><%= t :undone%></td>
            <% end %>
            <td><%= task.name %></td>
            <td><%= task.description %></td>
            <td><%= task.importance %></td>
            <td><%= task.expiry %></td>
            <td><%= link_to t(:update), edit_task_path(id: task.id), method: :get %></td>
            <td><%= link_to t(:delete), delete_task_path(id: task.id), method: :delete %></td>
          </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/tasks/new.html.erb
<div align="center">
  <h2>New task</h2>
  <h4>Please, enter the form</h4> </div>
<%= form_for :task do |f| -%>
      <p> Name   <%= f.text_field :name, placeholder: 'name' %></p>
    <p> Description  <%= f.text_field :description, placeholder: 'description' %></p>
    <p> Importance <%= f.text_field :importance, placeholder: 'importance' %></p>
    <p> Date <%= f.date_select :expiry, order: [:day, :month, :year] %></p>
    <p> <%= f.submit "Save" %>
     <%= link_to'Back', '/' %></p>
<% end %>